version: "3.7"

services:
  db:
    # psql -h localhost -p 5400 -U byt -W
    image: postgres:13
    ports:
      - 5400:5432
    environment:
      POSTGRES_DB: byt
      POSTGRES_USER: byt
      POSTGRES_PASSWORD: byt!123
    volumes:
      - ./resources/db.changelog/init.sql:/docker-entrypoint-initdb.d/init.sql